# Generated by Django 5.0.6 on 2024-05-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritesh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='project/')),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
