# Generated by Django 5.0.6 on 2024-05-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritesh', '0002_project_delete_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='resume',
            field=models.FileField(default=None, null=True, upload_to='resume/'),
        ),
    ]
