# Generated by Django 5.0.6 on 2024-05-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritesh', '0003_home_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Project', max_length=150),
            preserve_default=False,
        ),
    ]
